apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecopsproject-nginx
  labels:
    app: devsecopsproject-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecopsproject-nginx
  template:
    metadata:
      labels:
        app: devsecopsproject-nginx
    spec:
      containers:
      - name: nginx
        image: 992382806303.dkr.ecr.us-east-1.amazonaws.com/devsecopsproject-nginx:latest
        ports:
        - containerPort: 80
