apiVersion: v1
kind: Service
metadata:
  name: devsecopsproject-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: devsecopsproject-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
